-- ==========================================================================
-- PS3 category coverage -- run ps3_20260726, Chicago / CTA-Ventra
--
-- Generated by tooling/gen_ps3_coverage.py from ps3_run_summary.json and
-- Validator/validator_ps3_stub.json. Every figure and every sentence of the
-- exclusion reason is read out of those two artefacts.
--
-- NOT in migrate(). Applied by the explicit load_run action, like every other
-- file in sql/load/.
-- ==========================================================================

DELETE FROM ps3_category_coverage WHERE city_id='CHI' AND run_id='ps3_20260726';

INSERT INTO ps3_category_coverage
  (city_id, run_id, device_category, modeled, n_ps3_incidents, n_devices_scored,
   n_serials_scored, source_table, exclusion_reason, alternative_coverage,
   remediation, as_of_date) VALUES
  ('CHI', 'ps3_20260726', 'TVM', TRUE, 32842, 472, 472, 'mars_dev.silver.incident_root_cause (ServiceNow availability events)', NULL, NULL, NULL, '2026-07-26'),
  ('CHI', 'ps3_20260726', 'GATE', TRUE, 1770, 455, 455, 'mars_dev.silver.incident_root_cause (ServiceNow availability events)', NULL, NULL, NULL, '2026-07-26'),
  ('CHI', 'ps3_20260726', 'VALIDATOR', FALSE, 0, 0, 0, 'mars_dev.silver.incident_root_cause (ServiceNow availability events)', 'PS3 is sourced from silver.incident_root_cause (ServiceNow availability events). VALIDATOR/BMV failures are NOT recorded as availability events -- they surface as device_event out-of-service ''Set'' events (dim_event_matrix OOS flags). So the PS3 availability-event feed has 0 rows for this device type by construction.', 'Score validators via the PS4 anomaly head (unsupervised, covers all 3 types) and the OOS-proxy severity below; a true PS3 validator model needs Cubic to emit validator availability events or fault codes.', 'Cubic must emit validator availability events or fault codes into incident_root_cause. Until then the proxy feed is silver.device_failures (S26) OOS ''Set'' events, severity via dim_failure_level.', '2026-07-26');
