-- PS2 run backfill  (generated by PS2_enhanced.ipynb)
-- city=CHI  computed_date=2026-07-14  rows grounded in the real Gold run

-- ps2_cascade_window_summary  (5 rows)
DELETE FROM ps2_cascade_window_summary WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_cascade_window_summary (city_id, window_bucket, cascade_days, pct, total_cascade_days, slow_fast_fault_mult, slow_fast_duration_mult, computed_date) VALUES
  ('CHI', '0-5min', 0, 0.0000, 10, NULL, NULL, '2026-07-14'),
  ('CHI', '5-15min', 0, 0.0000, 10, NULL, NULL, '2026-07-14'),
  ('CHI', '15-30min', 0, 0.0000, 10, NULL, NULL, '2026-07-14'),
  ('CHI', '30-60min', 0, 0.0000, 10, NULL, NULL, '2026-07-14'),
  ('CHI', '60min+', 10, 100.0000, 10, NULL, NULL, '2026-07-14');

-- ps2_window_detail  (5 rows)
DELETE FROM ps2_window_detail WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_window_detail (city_id, window_bucket, cascade_days, chain_len_mean, chain_len_median, chain_len_max, span_min_mean, span_min_median, velocity_min_per_fault, computed_date) VALUES
  ('CHI', '0-5min', 0, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-14'),
  ('CHI', '5-15min', 0, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-14'),
  ('CHI', '15-30min', 0, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-14'),
  ('CHI', '30-60min', 0, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-14'),
  ('CHI', '60min+', 10, 8.1000, 6.0000, 29, 475.6680, 223.1330, 75.0240, '2026-07-14');

-- ps2_top_devices  (1 rows)
DELETE FROM ps2_top_devices WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_top_devices (city_id, device_id, category, cascade_days, w0_5, w5_15, w15_30, w30_60, w60plus, dev_rank, computed_date) VALUES
  ('CHI', 'BMV01005', 'VALIDATOR', 10, 0, 0, 0, 0, 10, 1, '2026-07-14');

-- ps2_subsystem_hub_summary  (3 rows)
DELETE FROM ps2_subsystem_hub_summary WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_subsystem_hub_summary (city_id, node_id, freq, is_hub, computed_date) VALUES
  ('CHI', 'COMMS', 100, TRUE, '2026-07-14'),
  ('CHI', 'SYSTEM', 100, TRUE, '2026-07-14'),
  ('CHI', 'DOPP', 70, TRUE, '2026-07-14');

-- ps2_subsystem_hub_edges  (0 rows)
DELETE FROM ps2_subsystem_hub_edges WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';

-- ps2_subsystem_associations  (12 rows)
DELETE FROM ps2_subsystem_associations WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_subsystem_associations (city_id, antecedent_subsystem, consequent_subsystem, support, confidence, lift, conviction, computed_date) VALUES
  ('CHI', 'DOPP', 'COMMS', 0.7000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'COMMS', 'DOPP', 0.7000, 0.7000, 1.0000, 1.0000, '2026-07-14'),
  ('CHI', 'COMMS', 'SYSTEM', 1.0000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'SYSTEM', 'COMMS', 1.0000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'DOPP', 'SYSTEM', 0.7000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'SYSTEM', 'DOPP', 0.7000, 0.7000, 1.0000, 1.0000, '2026-07-14'),
  ('CHI', 'COMMS, DOPP', 'SYSTEM', 0.7000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'DOPP, SYSTEM', 'COMMS', 0.7000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'COMMS, SYSTEM', 'DOPP', 0.7000, 0.7000, 1.0000, 1.0000, '2026-07-14'),
  ('CHI', 'DOPP', 'COMMS, SYSTEM', 0.7000, 1.0000, 1.0000, 99.0000, '2026-07-14'),
  ('CHI', 'COMMS', 'DOPP, SYSTEM', 0.7000, 0.7000, 1.0000, 1.0000, '2026-07-14'),
  ('CHI', 'SYSTEM', 'COMMS, DOPP', 0.7000, 0.7000, 1.0000, 1.0000, '2026-07-14');

-- ps2_facility_contagion_summary  (1 rows)
DELETE FROM ps2_facility_contagion_summary WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_facility_contagion_summary (city_id, total_facility_cascade_days, multi_device_contagion_pct, trend_start_pct, trend_end_pct, hotspot_facility_id, hotspot_facility_name, hotspot_min_devices, hotspot_max_devices, computed_date) VALUES
  ('CHI', 10, 0.0000, 0.0000, 0.0000, 42, 'Chicago', 1, 1, '2026-07-14');

-- ps2_cascade_paths  (10 rows)
DELETE FROM ps2_cascade_paths WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_cascade_paths (city_id, path_rank, cascade_path, path_len, first_subsystem, last_subsystem, occurrences, pct_of_chains, computed_date) VALUES
  ('CHI', 1, 'DOPP->DOPP->SYSTEM->COMMS', 4, 'DOPP', 'COMMS', 1, 10.0000, '2026-07-14'),
  ('CHI', 2, 'SYSTEM->COMMS->DOPP->DOPP', 4, 'SYSTEM', 'DOPP', 1, 10.0000, '2026-07-14'),
  ('CHI', 3, 'DOPP->DOPP->SYSTEM->COMMS->SYSTEM->SYSTEM', 6, 'DOPP', 'SYSTEM', 1, 10.0000, '2026-07-14'),
  ('CHI', 4, 'SYSTEM->COMMS->SYSTEM->COMMS->SYSTEM->COMMS', 6, 'SYSTEM', 'COMMS', 1, 10.0000, '2026-07-14'),
  ('CHI', 5, 'DOPP->DOPP->SYSTEM->COMMS->SYSTEM->COMMS', 6, 'DOPP', 'COMMS', 1, 10.0000, '2026-07-14'),
  ('CHI', 6, 'SYSTEM->COMMS->SYSTEM->SYSTEM->COMMS->SYSTEM', 6, 'SYSTEM', 'SYSTEM', 1, 10.0000, '2026-07-14'),
  ('CHI', 7, 'SYSTEM->COMMS->DOPP->DOPP->SYSTEM->COMMS->SYSTEM->COMMS', 8, 'SYSTEM', 'COMMS', 1, 10.0000, '2026-07-14'),
  ('CHI', 8, 'COMMS->SYSTEM->COMMS->SYSTEM->COMMS->DOPP->DOPP->SYSTEM', 8, 'COMMS', 'SYSTEM', 1, 10.0000, '2026-07-14'),
  ('CHI', 9, 'SYSTEM->COMMS->DOPP->DOPP->SYSTEM->SYSTEM->DOPP->DOPP->COMMS->SYSTEM->SYSTEM->SYSTEM->COMMS->DOPP->DOPP->SYSTEM->COMMS->SYSTEM->SYSTEM->COMMS->SYSTEM->DOPP->DOPP->COMMS->SYSTEM->SYSTEM->SYSTEM->COMMS->SYSTEM', 29, 'SYSTEM', 'SYSTEM', 1, 10.0000, '2026-07-14'),
  ('CHI', 10, 'SYSTEM->COMMS->SYSTEM->COMMS', 4, 'SYSTEM', 'COMMS', 1, 10.0000, '2026-07-14');

-- ps2_ignition_termination  (3 rows)
DELETE FROM ps2_ignition_termination WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_ignition_termination (city_id, subsystem, rank, ignition_days, termination_days, ignition_pct, termination_pct, net_role, computed_date) VALUES
  ('CHI', 'SYSTEM', 1, 6, 4, 60.0000, 40.0000, 'Ignitor', '2026-07-14'),
  ('CHI', 'COMMS', 2, 1, 5, 10.0000, 50.0000, 'Terminator', '2026-07-14'),
  ('CHI', 'DOPP', 3, 3, 1, 30.0000, 10.0000, 'Ignitor', '2026-07-14');

-- ps2_business_impact  (1 rows)
DELETE FROM ps2_business_impact WHERE city_id='CHI' AND computed_date=DATE '2026-07-14';
INSERT INTO ps2_business_impact (city_id, device_id, category, total_impact, cascade_days, avg_impact, max_impact, impact_rank, computed_date) VALUES
  ('CHI', 'BMV01005', 'VALIDATOR', 81.0000, 10, 8.1000, 29.0000, 1, '2026-07-14');

