-- ============================================================================
-- 18_purge_ps3_bridge_test_rows.sql            CUBIC MARS Chicago  2026-07-26
--
-- Purpose: remove non-production rows from the PS3 severity tables so every
-- number the dashboard draws traces back to a real SageMaker run artifact.
--
-- What this deletes, and why each row is not real:
--
--   ps3_severity_predictions WHERE incident_id LIKE 'INC-PS1-%'
--     Written by the 2026-07-13 PS1 -> PS3 bridge smoke test. The incident ids
--     were generated by the test harness (INC-PS1-0001 .. INC-PS1-000n), the
--     device ids do not resolve against silver.hw_config_current, and
--     actual_label is NULL on every row because no incident ever occurred.
--     They exist only to prove the insert path worked.
--
-- Idempotent: re-running deletes nothing further. Safe to include in migrate().
-- Nothing here touches the real ps3_severity_summary / ps3_severity_drivers /
-- ps3_device_metrics rows, which carry the 19-Jul run's measured metrics.
-- Nothing here touches the migration-15 two-head tables, which the PS3 v2
-- notebook run will populate.
-- ============================================================================

DELETE FROM ps3_severity_predictions
WHERE incident_id LIKE 'INC-PS1-%';

-- Guard: fail loudly at review time if anything synthetic is reintroduced.
-- (A comment, not a constraint -- the API also filters INC-PS1-% defensively.)
