"""
gen_ps3_coverage.py -- build sql/load/ps3_coverage_20260726.sql from the run
artefacts. Every value written here is read out of a file the SageMaker run
produced; nothing is typed in by hand except the SQL scaffolding.

Sources
    Level2/PS3/ps3_run_summary.json          device_scope, per-category modeled
                                             flag, n_incidents, n_devices,
                                             n_serials
    Level2/PS3/Validator/validator_ps3_stub.json
                                             the reason VALIDATOR is empty, the
                                             recommended alternative, and the
                                             proxy source -- written by the run,
                                             not by me.
"""
import json, os

ROOT = "/mnt/user-data/uploads/Level2/PS3"
OUT = ("/mnt/user-data/uploads/sathish_repo/api/lambda/cubic-mars-dashboard-api"
       "/sql/load/ps3_coverage_20260726.sql")
CITY, RUN, ASOF = "CHI", "ps3_20260726", "2026-07-26"

summary = json.load(open(os.path.join(ROOT, "ps3_run_summary.json")))
stub = json.load(open(os.path.join(ROOT, "Validator", "validator_ps3_stub.json")))

MODELLED_SOURCE = "mars_dev.silver.incident_root_cause (ServiceNow availability events)"


def q(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


rows = []
for r in summary["results"]:
    cat = r["cat"]
    modeled = bool(r.get("modeled"))
    if modeled:
        rows.append(dict(
            cat=cat, modeled=True,
            n_inc=int(r.get("n_incidents") or 0),
            n_dev=int(r.get("n_devices") or 0),
            n_ser=int(r.get("n_serials") or 0),
            source=MODELLED_SOURCE,
            reason=None,
            alt=None,
            remediation=None))
    else:
        # VALIDATOR. Text comes straight out of the stub the run wrote.
        rows.append(dict(
            cat=cat, modeled=False,
            n_inc=int(r.get("n_incidents") or 0), n_dev=0, n_ser=0,
            source=MODELLED_SOURCE,
            reason=stub["why"],
            alt=stub["recommendation"],
            remediation=("Cubic must emit validator availability events or fault codes into "
                         "incident_root_cause. Until then the proxy feed is "
                         + stub["proxy_source"] + ".")))

# Guard: the scope list and the results list must agree, or a category would be
# silently missing from the coverage table -- the exact failure this table exists
# to prevent.
scope = set(summary.get("device_scope") or [])
got = {x["cat"] for x in rows}
if scope != got:
    raise SystemExit(f"device_scope {sorted(scope)} != results {sorted(got)}")

hdr = f"""-- ==========================================================================
-- PS3 category coverage -- run {RUN}, Chicago / CTA-Ventra
--
-- Generated by tooling/gen_ps3_coverage.py from ps3_run_summary.json and
-- Validator/validator_ps3_stub.json. Every figure and every sentence of the
-- exclusion reason is read out of those two artefacts.
--
-- NOT in migrate(). Applied by the explicit load_run action, like every other
-- file in sql/load/.
-- ==========================================================================

DELETE FROM ps3_category_coverage WHERE city_id='{CITY}' AND run_id='{RUN}';

INSERT INTO ps3_category_coverage
  (city_id, run_id, device_category, modeled, n_ps3_incidents, n_devices_scored,
   n_serials_scored, source_table, exclusion_reason, alternative_coverage,
   remediation, as_of_date) VALUES
"""

vals = []
for x in sorted(rows, key=lambda z: -z["n_inc"]):
    vals.append(
        f"  ('{CITY}', '{RUN}', '{x['cat']}', {'TRUE' if x['modeled'] else 'FALSE'}, "
        f"{x['n_inc']}, {x['n_dev']}, {x['n_ser']}, {q(x['source'])}, "
        f"{q(x['reason'])}, {q(x['alt'])}, {q(x['remediation'])}, '{ASOF}')")

sql = hdr + ",\n".join(vals) + ";\n"
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(sql)

print(f"wrote {OUT}")
for x in rows:
    print(f"  {x['cat']:<10} modeled={x['modeled']!s:<5} incidents={x['n_inc']:>6,} "
          f"devices={x['n_dev']:>4} serials={x['n_ser']:>4}")
print(f"  longest exclusion_reason = {max((len(x['reason'] or '') for x in rows))} chars "
      f"(column is VARCHAR(600))")
print(f"  longest remediation      = {max((len(x['remediation'] or '') for x in rows))} chars "
      f"(column is VARCHAR(400))")
print(f"  longest alternative      = {max((len(x['alt'] or '') for x in rows))} chars "
      f"(column is VARCHAR(300))")
